#' Missing to NAs
#'
#' Converts values labelled as missings to \code{NA}.
#' 
#' @param tibble a tibble object.
#'
#' @returns A tibble.
#' 
#' @keywords tibblemanagement
#' 
#' @examples
#' # tibble generated by haven
#' input <- system.file("extdata/reds", package = "ILSAmerge")
#' tib <- do.call(rbind,justload(inputdir = input,population = "BCGV1"))
#' 
#' tib
#' 
#' mistoNAs(tib)
#'
#' @export
#

mistoNAs <- function(tibble){
  getnas <- get.nas(tibble)
  
  unt <- tibble
  unt <- lapply(1:ncol(unt), function(X) {
    as.vector(unt[, X, drop = TRUE])
  })
  unt <- do.call(cbind.data.frame, unt)
  colnames(unt) <- colnames(tibble)
  
  isna <- matrix(NA,nrow = nrow(unt), ncol = ncol(unt))
  for(i in 1:ncol(unt)){
    isna[,i] <- unt[,i]%in%getnas[[i]]
    
  }
  unt[isna] <- NA
  
  asthistibble(tibble,unt)
  
}